#!/usr/bin/env bash
#handles:
# - nginx must be running as nginx user
# - nginx must be listening to all active IPs on port 8080

pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_seever/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
